planar3dof:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Effort Controllers ---------------------------------------
  joint0_position_controller:
    type: effort_controllers/JointEffortController
    joint: joint0
    pid: {p: 1.0, i: 0.1, d: 0.01}
  joint1_position_controller:
    type: effort_controllers/JointEffortController
    joint: joint1
    pid: {p: 1.0, i: 0.1, d: 0.01}
  joint2_position_controller:
    type: effort_controllers/JointEffortController
    joint: joint2
    pid: {p: 1.0, i: 0.1, d: 0.01}

